name: physioscope
description: "Interactive physiognomy analysis application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State Management
  flutter_riverpod: ^2.4.9
  
  # UUID generation
  uuid: ^4.3.3
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#9FA8DA"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  generate: true
